[package]
name = "soundkit-opus"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Opus Encoder traits"
repository = "https://github.com/wavey-ai/soundkit"
readme = "README.md"

[dependencies]
libopus = { git = "https://github.com/wavey-ai/opus-rs" }
soundkit = { version = "0.12.1", path = "../soundkit" }
frame-header = { git = "https://github.com/wavey-ai/frame-header.git" }
tracing = "0.1.40"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
[lib]
crate-type = ["cdylib", "rlib"]
